spring.application-name: spring-security-aws
server.port: 33517

spring:
  datasource:
    username: postgres
    password: password123
    url: jdbc:postgresql://localhost:5432/users
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect

  security:
    listeners: com.akarsh.aws.examples.security.config.listeners.AuthenticationSuccessListener

logging:
  file: ./spring-security.log
  level:
    org.springframework.security: TRACE
#    root: TRACE


