/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.akarsh.aws.examples.sqs;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppTest {
    @Test
    public void contextLoads() {}
}
